name: LoupGarou

version: 0.1

author: Val'entin

main: fr.valentin.loupgarou.LoupGarou


commands:

  LoupGarou:
    description: LoupGarou commands
    aliases: lg
    usage: /lg <start|help>

  LoupGarouSetup:
    description: LoupGarou setup commands
    aliases: lgs
    usage: /lgs <spawn|spawnHumain|spawnLoup>